name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write' # Necessário para o auth do GCP

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Autenticar com o Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_PROVIDER }}'
          service_account: 'cloud-run-deployer@monitor-cotacoes.iam.gserviceaccount.com'

      - name: Instalar CLI do Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Build e push da imagem Docker
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/monitor-cotacoes

      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy monitor-cotacoes \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/monitor-cotacoes \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 512Mi \
            --min-instances 0 \
            --service-account cloud-run-deployer@monitor-cotacoes.iam.gserviceaccount.com
